version: '3.8'
services:
  app:
    build: .
    ports:
      - '3001:3001'
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_permissions
